### ISSUE TITLE
[Feature Request] Add localization support

### ISSUE THREAD

**Issue by kryptonit1** [IBM/mac-ibm-migration-tool#6]
**Is your feature request related to a problem? Please describe.**
The migration app is only available in English.

**Describe the solution you'd like**
It would be nice if it would be possible to translate/localize the migration app via a configuration profile in order to allow the information and button labels in the app to be translated to other languages.

**Describe alternatives you've considered**
Adding support for other languages directly into the migration app and automatically select the app language based on the configured macOS language on the device that the migration app is running on.

**Additional context**
None

**Comment by SMartorelli** [comment]
Hi @kryptonit1, the app already supports localization. This can be achieved by adding a new language in the Localizable.strings file in Xcode. Localization is only possible by customizing the project before building the app. Xcode makes it pretty easy, as you can see.

![Screenshot 2024-10-17 at 10 52 48](https://github.com/user-attachments/assets/9a992b9e-7011-4b77-a28e-aa512edea0e7)

It also tracks the percentage of completion. I'll create a guide on how to add new localizations in Xcode and will use this issue to track it.
It's not practical to achieve this through a configuration profile.

**Comment by kryptonit1** [comment]
Oh, great! Thank you! Will try that out.
